module Services
  module AmountsOfActivityAction

    LOST_MINOR_FEEDING = -1
    LOST_SMALL_FEEDING = -2
    LOST_NORMAL_FEEDING = -3
    LOST_LARGE_FEEDING = -4
    LOST_EXTRA_FEEDING = -5

    LOST_MINOR_ACTIVITY =  -2
    LOST_SMALL_ACTIVITY = -4
    LOST_NORMAL_ACTIVITY = -6
    LOST_LARGE_ACTIVITY = -8
    LOST_EXTRA_ACTIVITY = -1

    ADDED_MINOR_AMOUNT = 2
    ADDED_SMALL_AMOUNT = 4
    ADDED_NORMAL_AMOUNT = 6
    ADDED_LARGE_AMOUNT = 8
    ADDED_EXTRA_AMOUNT = 10

    ADDED_MINOR_HAPPINESS = 1
    ADDED_SMALL_HAPPINESS = 2
    ADDED_NORMAL_HAPPINESS = 3
    ADDED_LARGE_HAPPINESS = 4
    ADDED_EXTRA_HAPPINESS = 5

  end
end