module Services
  module AmountsOfPlayingAction

    LOST_MINOR_FEEDING = -5
    LOST_SMALL_FEEDING = -10
    LOST_NORMAL_FEEDING = -15
    LOST_LARGE_FEEDING = -20
    LOST_EXTRA_FEEDING = -25

    LOST_MINOR_ACTIVITY =  -1
    LOST_SMALL_ACTIVITY = -2
    LOST_NORMAL_ACTIVITY = -3
    LOST_LARGE_ACTIVITY = -4
    LOST_EXTRA_ACTIVITY = -5

    PAID_MINOR_AMOUNT = -1
    PAID_SMALL_AMOUNT = -2
    PAID_NORMAL_AMOUNT = -3
    PAID_LARGE_AMOUNT = -4
    PAID_EXTRA_AMOUNT = -5

    ADDED_MINOR_HAPPINESS = 2
    ADDED_SMALL_HAPPINESS = 4
    ADDED_NORMAL_HAPPINESS = 6
    ADDED_LARGE_HAPPINESS = 8
    ADDED_EXTRA_HAPPINESS = 10

  end
end