module Services
  module AmountOfActions

    ADDED_MINOR_FEEDING = 5
    ADDED_SMALL_FEEDING = 10
    ADDED_NORMAL_FEEDING = 15
    ADDED_LARGE_FEEDING = 20
    ADDED_EXTRA_FEEDING = 25

    LOST_MINOR_ACTIVITY =  1
    LOST_SMALL_ACTIVITY = 2
    LOST_NORMAL_ACTIVITY = 3
    LOST_LARGE_ACTIVITY = 4
    LOST_EXTRA_ACTIVITY = 5

    PAID_MINOR_AMOUNT = 5
    PAID_SMALL_AMOUNT = 10
    PAID_NORMAL_AMOUNT = 15
    PAID_LARGE_AMOUNT = 20
    PAID_EXTRA_AMOUNT = 25

    ADDED_MINOR_HAPPINESS = 1
    ADDED_SMALL_HAPPINESS = 2
    ADDED_NORMAL_HAPPINESS = 3
    ADDED_LARGE_HAPPINESS = 4
    ADDED_EXTRA_HAPPINESS = 5

  end
end